project_id_env: "CROWDIN_PROJECT_ID"
api_token_env: "CROWDIN_PERSONAL_TOKEN"

preserve_hierarchy: true

files:
  - source: '/play-services-base/core/src/main/res/values/strings.xml'
    translation: '/play-services-base/core/src/main/values-%android_code%/values/strings.xml'
    dest: '/microG/base.xml'
    skip_untranslated_strings: true

  - source: '/play-services-core/src/main/res/values/plurals.xml'
    translation: '/play-services-core/src/main/res/values-%android_code%/plurals.xml'
    dest: '/microG/core_plurals.xml'
    skip_untranslated_strings: true

  - source: '/play-services-core/src/main/res/values/strings.xml'
    translation: '/play-services-core/src/main/res/values-%android_code%/strings.xml'
    dest: '/microG/core.xml'
    skip_untranslated_strings: true

  - source: '/play-services-core/microg-ui-tools/src/main/res/values/strings.xml'
    translation: '/play-services-core/microg-ui-tools/src/main/res/values-%android_code%/strings.xml'
    dest: '/microG/core_ui.xml'
    skip_untranslated_strings: true
